[package]
name = "lit"
version = "0.2.3"
authors = ["Dylan McKay <me@dylanmckay.io>"]

description = "Integrated testing tool"
documentation = "https://docs.rs/lit"
repository = "https://github.com/dylanmckay/lit"

license = "MIT"

keywords = ["testing"]

[dependencies]
walkdir = "1.0"
term = "0.4"
regex = "0.2"
argparse = "0.2"
